services:
  app:
    container_name: laravel-app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    volumes:
      - .:/var/www
#      - /var/www/vendor
      - /var/www/node_modules
    networks:
      - laravel
    depends_on:
      - db

  nginx:
    container_name: laravel-nginx
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    container_name: laravel-db
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: postgre
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - laravel

  node:
    container_name: laravel-node
    image: node:20-alpine
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/node_modules
    ports:
      - "5173:5173"
    networks:
      - laravel
    tty: true
    command: sh -c "npm install && npm run dev"

  workspace:
    container_name: laravel-workspace
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    volumes:
      - .:/var/www
#      - /var/www/vendor
    working_dir: /var/www
    tty: true
    networks:
      - laravel
    entrypoint: ["/bin/sh"]

volumes:
  db-data:

networks:
  laravel:
    driver: bridge
